version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    groups:
      all-minor-updates:
        update-types:
          - "minor"
          - "patch"
